# -*- coding: utf-8 -*-
"""Aplicaciones_Termodinamicas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XXV0lv6_mqQM3x0vN2jovoMko4xUe305
"""

!pip install streamlit -q
!pip install iapws -q

!pip install streamlit numpy scipy matplotlib yt-dlp pydub

!mkdir -p pages

"""PAGINA PRINCIPAL

"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Introducción.py
# import streamlit as st
# 
# st.set_page_config(
#     page_title=" Aplicaciones Termodinámicas",
#     page_icon="📊",
#     layout="wide"
# )
# 
# custom_css = """
# <style>
#     .stApp {
#         background-color: #999999; /* Fondo principal de toda la app */
#         color: #E0E0E0;            /* Color de texto general */
#         font-family: 'Courier New', monospace; /* Fuente tipo monoespaciada */
#     }
# 
#     h1, h2, h3 {
#         color: #00BFFF;                  /* Color del texto de títulos */
# 
#     }
# 
#     .main .block-container {
#         padding-top: 2rem;               /* Espaciado arriba */
#         padding-bottom: 2rem;            /* Espaciado abajo */
#         background-color: #1B1D2B;       /* Fondo de los bloques principales */
#         border-radius: 10px;             /* Bordes redondeados */
#     }
# 
#     section[data-testid="stSidebar"] {
#         background-color: #bcbcbc;       /* Fondo del sidebar (barra lateral) */
#         border-radius: 10px;             /* Bordes redondeados del sidebar */
#     }
# </style>
# """
# st.markdown(custom_css, unsafe_allow_html=True)
# 
# st.title("Bienvenido a Simulaciones Interactivas de termodinamica")
# st.sidebar.success("Selecciona una página arriba.")
# 
# st.markdown(
#     """
#     ¡Hola! Bienvenido a este espacio interactivo donde puedes explorar diferentes conceptos
#     de Termodinámica   a través de simulaciones prácticas.
# 
#     **👈 Selecciona una aplicación del menú de la izquierda** para empezar.
# 
#     Puedes encontrar simulaciones para:
#     - **Análisis de Toberas:** Explora cómo cambian la velocidad y presión del aire.
#     - **Cálculo de Condensadores:** Determina el flujo de agua de enfriamiento necesario.
#     """
# )

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Tobera.py
# # pages/Tobera.py – Dashboard interactivo para análisis de tobera
# 
# import streamlit as st
# import numpy as np
# 
# # =========================
# # 🎨 Estilo Retro Gamer Azul (heredado)
# # =========================
# custom_css = """
# <style>
#     .stApp {
#         background-color: #0D0F1A; /* Fondo principal de toda la app */
#         color: #E0E0E0;            /* Color de texto general */
#         font-family: 'Courier New', monospace; /* Fuente tipo monoespaciada */
#     }
# 
#     h1, h2, h3 {
#         color: #00BFFF;                  /* Color del texto de títulos */
# 
#     }
# 
#     .main .block-container {
#         padding-top: 2rem;               /* Espaciado arriba */
#         padding-bottom: 2rem;            /* Espaciado abajo */
#         background-color: #1B1D2B;       /* Fondo de los bloques principales */
#         border-radius: 10px;             /* Bordes redondeados */
#     }
# 
#     section[data-testid="stSidebar"] {
#         background-color: #16537e;       /* Fondo del sidebar (barra lateral) */
#         border-radius: 10px;             /* Bordes redondeados del sidebar */
#     }
# </style>
# """
# st.markdown(custom_css, unsafe_allow_html=True)
# 
# # =========================
# # 📝 Constantes globales
# # =========================
# R_kJ_kgK = 0.287   # kJ/kg·K
# Cp_kJ_kgK = 1.005  # kJ/kg·K
# 
# # =========================
# # 📝 Función de análisis de tobera
# # =========================
# 
# def analizar_tobera(P1_kPa, T1_C, V1_ms, A1_cm2, P2_kPa, V2_ms):
#     P1_Pa, P2_Pa = P1_kPa * 1000, P2_kPa * 1000
#     T1_K = T1_C + 273.15
#     A1_m2 = A1_cm2 / 1e4
# 
#     v1 = (R_kJ_kgK * 1000 * T1_K) / P1_Pa
#     m_dot = (A1_m2 * V1_ms) / v1
# 
#     Cp_J = Cp_kJ_kgK * 1000
#     delta_T = (V1_ms**2 - V2_ms**2) / (2 * Cp_J)
#     T2_K = T1_K + delta_T
#     T2_C = T2_K - 273.15
# 
#     v2 = (R_kJ_kgK * 1000 * T2_K) / P2_Pa
#     A2_m2 = (m_dot * v2) / V2_ms
#     A2_cm2 = A2_m2 * 1e4
# 
#     return {
#         "m_dot": m_dot,
#         "T2_C": T2_C,
#         "T2_K": T2_K,
#         "A2_cm2": A2_cm2,
#         "ratio": A2_m2 / A1_m2,
#         "v1": v1,
#         "v2": v2
#     }
# 
# # =========================
# # 🚀 Interfaz Streamlit
# # =========================
# col_img, col_title = st.columns([0.2, 1])
# with col_img:
#     st.image("https://raw.githubusercontent.com/Jmontoyaor/thermodynamics/main/Toberas.png", width=200)
# with col_title:
#     st.title("Tobera: Análisis interactivo de Tobera de Aire")
# st.markdown("#### Explora cómo varían la velocidad, la presión y la temperatura en una tobera.")
# st.write("---")
# 
# 
# 
# # =========================
# # 📘 Teoría
# # =========================
# with st.expander("📘 Fundamentos Termodinámicos de Toberas y Difusores (Çengel, 7ª ed.)"):
#     st.markdown(r"""
# Las **toberas** y los **difusores** son dispositivos fundamentales en sistemas de propulsión como motores a chorro, cohetes, turbinas de gas y también en aplicaciones industriales.
# - Una **tobera** incrementa la **velocidad del fluido** a costa de una **disminución de la presión**.
# - Un **difusor**, en cambio, **disminuye la velocidad** del fluido mientras **aumenta su presión**.
# 
# Ambos dispositivos están diseñados para modificar la energía cinética del fluido que los atraviesa, y **no implican trabajo mecánico** ($\dot{W} \equiv 0$), ni transferencia de calor significativa ($\dot{Q} \approx 0$), y el cambio de energía potencial es despreciable ($\Delta ep \approx 0$).
# 
# Por ello, la **conservación de energía** (1ª Ley de la Termodinámica para sistemas abiertos) se simplifica en estos casos a:
# 
# $$
# h_1 + \frac{V_1^2}{2} = h_2 + \frac{V_2^2}{2}
# $$
# 
# donde:
# - $h = C_p T$ es la entalpía específica
# - $V$ es la velocidad del flujo
# 
# Esto permite determinar la **temperatura de salida** $T_2$ si se conocen $T_1$, $V_1$ y $V_2$.
# 
# Asimismo, al aplicar la ecuación de conservación de masa:
# 
# $$
# \dot{m} = \frac{A_1 V_1}{v_1} = \frac{A_2 V_2}{v_2}
# $$
# 
# es posible calcular el **área de salida** $A_2$, siendo:
# - $v = \dfrac{RT}{P}$ el volumen específico del aire como gas ideal.
# 
# 📚 **Fuente**: Çengel, Yunus A., *Termodinámica*, 7ª Edición, McGraw-Hill, Sección 5.4 "Toberas y Difusores", pp. 278–279.
# """)
# 
# # =========================
# # 🧪 Ejercicio y Figura
# # =========================
# col1, col2 = st.columns(2)
# with col1:
#     with st.expander("🧪 Ejercicio Propuesto – Toberas"):
#         st.markdown("""
# **Primera ley de la termodinámica – Sistemas Abiertos**
# 
# **TOBERAS**
# 
# La entrada de una tobera tiene una sección de 100 cm², y por ella entra aire a una velocidad de 50 m/s, con una presión de 350 kPa y una temperatura de 227 °C. Luego sale a una velocidad de 190 m/s y una presión de 120 kPa. Determinar:
# 
# - a) El flujo másico de aire que circula por la tobera
# - b) La temperatura del aire a la salida de la tobera
# - c) El área de sección de salida de la tobera
# - d) La relación de áreas de entrada y salida
# """)
# with col2:
#     st.image("https://github.com/Jmontoyaor/thermodynamics/blob/main/Imagen%201.png?raw=true",
#              caption="**FIGURA 5-25** – La forma de toberas y difusores es tal que causan grandes cambios en la velocidad del fluido y, por lo tanto, en la energía cinética.\\n\\nFuente: Çengel – Termodinámica, 7ª Edición.")
# 
# # Sidebar – Parámetros de entrada
# tsidebar = st.sidebar
# tsidebar.header("📥 Parámetros de Entrada")
# P1 = tsidebar.number_input("Presión de entrada P₁ [kPa]", 50.0, 1000.0, 350.0, step=10.0)
# T1 = tsidebar.number_input("Temperatura de entrada T₁ [°C]", -50.0, 800.0, 227.0, step=5.0)
# V1 = tsidebar.number_input("Velocidad de entrada V₁ [m/s]", 1.0, 500.0, 50.0, step=1.0)
# A1 = tsidebar.number_input("Área de entrada A₁ [cm²]", 1.0, 1000.0, 100.0, step=1.0)
# P2 = tsidebar.number_input("Presión de salida P₂ [kPa]", 5.0, 1000.0, 120.0, step=5.0)
# V2 = tsidebar.number_input("Velocidad de salida V₂ [m/s]", 1.0, 1000.0, 190.0, step=1.0)
# 
# if tsidebar.button("💡 Calcular"):
#     res = analizar_tobera(P1, T1, V1, A1, P2, V2)
# 
#     st.subheader("📊 Resultados del Análisis")
#     st.metric("Flujo másico ṁ", f"{res['m_dot']:.3f} kg/s")
#     st.metric("Temperatura de salida T₂", f"{res['T2_C']:.2f} °C  ({res['T2_K']:.2f} K)")
#     st.metric("Área de salida A₂", f"{res['A2_cm2']:.2f} cm²")
#     st.metric("Relación de áreas A₂/A₁", f"{res['ratio']:.4f}")
# 
#     with st.expander("🔍 Detalles de los Cálculos"):
#         st.write(
#             f"""
#             - **Volumen específico entrada (v₁):** {res['v1']:.5f} m³/kg
#             - **Volumen específico salida (v₂):** {res['v2']:.5f} m³/kg
#             - **Constante del gas R:** {R_kJ_kgK} kJ/kg·K
#             - **Calor específico Cp:** {Cp_kJ_kgK} kJ/kg·K
#             """
#         )
# 
# # =========================
# # 👤 Créditos
# # =========================
# st.markdown("---")
# 
# st.caption("Developed by Juan Fernando Montoya Ortiz -Electrical Engineering Student -Universidad Nacional de Colombia")
#

!mv Tobera.py pages/

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Condensador.py
# import streamlit as st
# from iapws import IAPWS97
# import sys
# 
# # Se agregan las clases .resultado-final y .nota-info para los nuevos colores.
# custom_css = """
# 
# <style>
#     .stApp {
#         background-color: #244811; /* Fondo principal de toda la app */
#         color: #E0E0E0;             /* Color de texto general */
#         font-family: 'Courier New', monospace; /* Fuente tipo monoespaciada */
#     }
# 
#     h1, h2, h3 {
#         color: #00BFFF;             /* Color del texto de títulos */
# 
#     }
# 
#     .main .block-container {
#         padding-top: 2rem;        /* Espaciado arriba */
#         padding-bottom: 2rem;     /* Espaciado abajo */
#         background-color: #1B1D2B;/* Fondo de los bloques principales */
#         border-radius: 10px;      /* Bordes redondeados */
#     }
# 
#     section[data-testid="stSidebar"] {
#         background-color: #38761d; /* Fondo del sidebar (barra lateral) */
#         border-radius: 10px;       /* Bordes redondeados del sidebar */
#     }
# 
#     /* Estilo para el cuadro del resultado final */
#     .resultado-final {
#         color: #FFD700; /* Color Dorado para las letras */
#         background-color: #2c3e50;
#         border: 1px solid #FFD700;
#         border-radius: 8px;
#         padding: 1rem;
#         text-align: center;
#         font-size: 1.1rem;
#     }
# 
#     /* Estilo para el texto de la nota */
#     .nota-info {
#         color: #98FB98; /* Color Verde Pálido para las letras */
#     }
# </style>
# """
# st.markdown(custom_css, unsafe_allow_html=True)
# 
# 
# 
# 
# 
# def calcular_flujo_enfriamiento(m_dot_v_kg_min, P_kPa, calidad_vapor, delta_T_agua_C):
#     """
#     Calcula el flujo másico de agua de enfriamiento necesario en un condensador.
# 
#     Utiliza la Primera Ley de la Termodinámica para sistemas abiertos en estado
#     estacionario. Las propiedades del vapor se obtienen con el estándar IAPWS-IF97.
# 
#     Args:
#         m_dot_v_kg_min (float): Flujo másico del vapor de entrada en kg/min.
#         P_kPa (float): Presión del vapor de entrada en kPa.
#         calidad_vapor (float): Calidad del vapor de entrada (un valor entre 0 y 1).
#         delta_T_agua_C (float): Aumento de temperatura permitido para el agua de
#                                  enfriamiento en grados Celsius.
# 
#     Returns:
#         dict: Un diccionario con todos los resultados de los cálculos.
#         None: Si ocurre un error (ej. presión fuera de rango).
#     """
#     # --- Constantes ---
#     # Calor específico del agua líquida en kJ/kg*°C
#     CP_AGUA = 4.18
# 
#     # --- Paso 1: Conversión de Unidades ---
#     # Convertir el flujo másico del vapor de kg/min a kg/s
#     m_dot_v_kg_s = m_dot_v_kg_min / 60.0
# 
#     # --- Paso 2: Propiedades Termodinámicas del Vapor ---
#     # La librería iapws requiere la presión en MPa
#     P_MPa = P_kPa / 1000.0
# 
#     # Crear objetos para el estado de líquido y vapor saturado a la presión dada
#     try:
#         liq_saturado = IAPWS97(P=P_MPa, x=0)
#         vap_saturado = IAPWS97(P=P_MPa, x=1)
#     except ValueError as e:
#         st.error(f"Error: La presión {P_kPa} kPa está fuera del rango válido para el modelo IAPWS-97. {e}")
#         return None
#     except Exception as e:
#         st.error(f"Ocurrió un error inesperado al obtener propiedades del vapor: {e}")
#         return None
# 
#     # Obtener entalpías específicas (h_f y h_g) en kJ/kg
#     h_f = liq_saturado.h  # Entalpía del líquido saturado
#     h_g = vap_saturado.h  # Entalpía del vapor saturado
#     h_fg = h_g - h_f      # Entalpía de vaporización
# 
#     # --- Paso 3: Cálculo de Entalpías en Entrada y Salida ---
#     # Entalpía del vapor a la entrada (mezcla líquido-vapor)
#     h_entrada = h_f + calidad_vapor * h_fg
# 
#     # Entalpía a la salida (líquido saturado)
#     h_salida = h_f
# 
#     # Diferencia de entalpía del vapor
#     delta_h_v = h_entrada - h_salida
# 
#     # --- Paso 4: Calor Liberado por el Vapor (Tasa de Transferencia) ---
#     # Q_punto es la energía transferida por unidad de tiempo en kW
#     Q_punto_kW = m_dot_v_kg_s * delta_h_v
# 
#     # --- Paso 5: Cálculo del Flujo Másico del Agua de Enfriamiento ---
#     # Q_punto = m_dot_a * cp_agua * Delta_T
#     # Despejamos el flujo másico del agua (m_dot_a)
#     if delta_T_agua_C == 0:
#         st.warning("El incremento de temperatura del agua no puede ser cero. Por favor, ingrese un valor mayor que cero.")
#         return None
#     m_dot_a_kg_s = Q_punto_kW / (CP_AGUA * delta_T_agua_C)
# 
#     # --- Empaquetar resultados ---
#     resultados = {
#         "m_dot_v_kg_s": m_dot_v_kg_s,
#         "P_kPa": P_kPa,
#         "calidad_vapor": calidad_vapor,
#         "delta_T_agua_C": delta_T_agua_C,
#         "h_f_kJ_kg": h_f,
#         "h_g_kJ_kg": h_g,
#         "h_fg_kJ_kg": h_fg,
#         "h_entrada_kJ_kg": h_entrada,
#         "h_salida_kJ_kg": h_salida,
#         "Q_punto_kW": Q_punto_kW,
#         "m_dot_a_kg_s": m_dot_a_kg_s
#     }
#     return resultados
# 
# # --- Diseño de la aplicación Streamlit ---
# st.set_page_config(
#     page_title="Cálculo de Condensador",
#     page_icon="💨",
#     layout="wide"
# )
# 
# # --- Barra Lateral (Sidebar) ---
# st.sidebar.header("1. Datos de Entrada")
# 
# flujo_masico_vapor = st.sidebar.slider(
#     "Flujo másico de vapor (kg/min)",
#     min_value=1.0, max_value=1000.0, value=420.0, step=1.0,
#     help="Flujo másico del vapor que entra al condensador."
# )
# presion_vapor = st.sidebar.slider(
#     "Presión del vapor (kPa)",
#     min_value=5.0, max_value=2000.0, value=30.0, step=0.1,
#     help="Presión a la que se encuentra el vapor."
# )
# calidad_inicial = st.sidebar.slider(
#     "Calidad del vapor (x)",
#     min_value=0.0, max_value=1.0, value=0.90, step=0.01,
#     help="Fracción de masa de vapor en la mezcla (0=líquido saturado, 1=vapor saturado)."
# )
# delta_temperatura = st.sidebar.slider(
#     "Incremento de temperatura del agua (°C)",
#     min_value=1.0, max_value=30.0, value=10.0, step=0.5,
#     help="Aumento de temperatura permitido para el agua de enfriamiento."
# )
# 
# # --- Contenido Principal ---
# col_img, col_title = st.columns([0.2, 1])
# with col_img:
#     st.image("https://raw.githubusercontent.com/Jmontoyaor/thermodynamics/main/Intercambiador%20de%20calor%20moderno.png", width=200)
# with col_title:
#     st.title("Intercambiador de calor: Análisis interactivo de Intercambiador de calor")
# st.markdown("""
# **Este módulo interactivo** te permite analizar las condiciones de operación de un intercambiador de calor de forma sencilla.
# Podrás observar cómo cambian variables clave como **presión**, **temperatura** y **velocidad** del fluido, y calcular parámetros importantes como el **flujo másico de enfriamiento necesario**.
# """)
# 
# st.write("---")
# 
# # --- Ejercicio Propuesto ---
# 
# st.subheader("📌 Ejercicio Propuesto")
# 
# st.write("""
# Al **Condensador** de una Termoeléctrica entran **420 kg/min de Vapor** con una
# **Presión de 30 kPa** y una **Calidad del 90%**; se requiere que el vapor
# salga como **líquido saturado**.
# Para enfriar el vapor, se utiliza **agua de un río**, haciéndola pasar por el interior del condensador.
# Para prevenir la contaminación térmica, el **agua del río** no debe superar un incremento
# de temperatura igual a **10 °C**.
# 
#  **Calcular:**
# El **flujo másico de agua de enfriamiento** necesario para satisfacer el cambio demandado por el vapor.
# """)
# 
# st.markdown("---")
# 
# # --- Columnas para Teoría e Imagen ---
# col1, col2 = st.columns(2)
# 
# with col1:
#     with st.expander("📘 Fundamentos Termodinámicos de Intercambiadores de Calor (Çengel, 7ª ed.)", expanded=False):
#         st.subheader("Intercambiadores de Calor")
#         st.write("""
#         Como su nombre indica, los **intercambiadores de calor** son dispositivos donde dos corrientes de fluido en movimiento intercambian calor sin mezclarlo. Los intercambiadores de calor se usan ampliamente en varias industrias y su diseño es variado.
# 
#         La forma más simple es un **intercambiador de calor de tubo doble** (o de tubo y coraza), que se compone de dos tubos concéntricos. Un fluido corre por el tubo interno mientras otro lo hace en el espacio anular. El calor se transfiere del fluido caliente al frío a través de la pared que los separa.
# 
#         **Principios Clave:**
#         - **Conservación de la masa:** En operación estacionaria, el flujo másico de cada fluido que fluye por el intercambiador permanece constante.
#         - **Energía:** Comúnmente, el trabajo (W) y los cambios de energía cinética y potencial son insignificantes. La tasa de transferencia de calor ($$\\dot{Q}$$) depende del volumen de control seleccionado. Si se analiza todo el dispositivo (asumiendo que está bien aislado), $$\\dot{Q} \\approx 0$$. Si se analiza solo uno de los fluidos, $$\\dot{Q}$$ representa el calor transferido entre los fluidos.
#         """)
#         st.caption("Referencia: Çengel, Y. A., & Boles, M. A. (2011). *Termodinámica* (7ª ed.). McGraw-Hill.")
# 
# 
# with col2:
#     st.image(
#         "https://github.com/Jmontoyaor/thermodynamics/blob/main/Imagen%202.png?raw=true",
#         caption="Figura 5-35, Un intercambiador de calor puede ser tan simple como dos tuberías concéntricas. Fuente: Çengel – Termodinámica, 7ª Edición.",
#         use_container_width=True
#     )
# 
# st.markdown("---")
# 
# st.header("2. Resultados del Cálculo")
# 
# if st.sidebar.button("Calcular Flujo de Enfriamiento", use_container_width=True):
#     resultados_calculados = calcular_flujo_enfriamiento(
#         m_dot_v_kg_min=flujo_masico_vapor,
#         P_kPa=presion_vapor,
#         calidad_vapor=calidad_inicial,
#         delta_T_agua_C=delta_temperatura
#     )
# 
#     if resultados_calculados:
#         st.subheader("Datos de Entrada Utilizados:")
#         st.write(f"- **Flujo másico de vapor (ṁ_v):** {flujo_masico_vapor:.1f} kg/min ({resultados_calculados['m_dot_v_kg_s']:.2f} kg/s)")
#         st.write(f"- **Presión del vapor (P):** {presion_vapor} kPa")
#         st.write(f"- **Calidad del vapor (x):** {calidad_inicial:.2f}")
#         st.write(f"- **Incremento de temp. del agua (ΔT):** {delta_temperatura} °C")
# 
#         st.subheader(f"Propiedades del Vapor (a {presion_vapor} kPa):")
#         st.write(f"- **Entalpía del líquido saturado ($h_f$):** {resultados_calculados['h_f_kJ_kg']:.2f} kJ/kg")
#         st.write(f"- **Entalpía del vapor saturado ($h_g$):** {resultados_calculados['h_g_kJ_kg']:.2f} kJ/kg")
#         st.write(f"- **Entalpía de vaporización ($h_{{fg}}$):** {resultados_calculados['h_fg_kJ_kg']:.2f} kJ/kg")
# 
#         st.subheader("Balance de Energía para el Vapor:")
#         st.write(f"- **Entalpía de entrada ($h_{{entrada}}$):** {resultados_calculados['h_entrada_kJ_kg']:.2f} kJ/kg")
#         st.write(f"- **Entalpía de salida ($h_{{salida}}$):** {resultados_calculados['h_salida_kJ_kg']:.2f} kJ/kg")
#         st.write(f"**- Tasa de calor liberado por el vapor ($\\dot{{Q}}$):** {resultados_calculados['Q_punto_kW']:.2f} kW")
# 
#         st.markdown("---")
#         # Se reemplaza st.success con st.markdown para usar la clase CSS personalizada.
#         st.markdown("<div class='resultado-final'>", unsafe_allow_html=True)
# 
#         st.latex( rf"""\textbf{{Flujo másico de agua de enfriamiento necesario }} (\dot{{m}}_{{a}}) = {resultados_calculados['m_dot_a_kg_s']:.2f} \; \text{{kg/s}}""")
# 
#         st.markdown("</div>", unsafe_allow_html=True)
# 
#     else:
#         st.warning("No se pudo realizar el cálculo. Por favor, revise los datos de entrada.")
# 
# st.markdown("---")
# # Se reemplaza st.info con st.markdown para usar la clase CSS personalizada.
# st.markdown("""
# <div class='nota-info'>
# <b>Nota sobre la precisión:</b> Este script utiliza el estándar internacional IAPWS-IF97 para obtener las propiedades termodinámicas del agua y el vapor, lo que garantiza una alta precisión en los cálculos. Los resultados pueden diferir ligeramente de los obtenidos con tablas de vapor antiguas.
# </div>
# """, unsafe_allow_html=True)
# 
# 
# st.markdown("---")
# st.caption("Developed by Juan Fernando Montoya Ortiz -Electrical Engineering Student -Universidad Nacional de Colombia")
#

!mv Condensador.py pages/

!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
!mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

#Ejecutar Streamlit
!streamlit run Introducción.py &>/content/logs.txt & #Cambiar 0_👋_Hello.py por el nombre de tu archivo principal

#Exponer el puerto 8501 con Cloudflare Tunnel
!cloudflared tunnel --url http://localhost:8501 > /content/cloudflared.log 2>&1 &

#Leer la URL pública generada por Cloudflare
import time
time.sleep(5)  # Esperar que se genere la URL

import re
found_context = False  # Indicador para saber si estamos en la sección correcta

with open('/content/cloudflared.log') as f:
    for line in f:
        #Detecta el inicio del contexto que nos interesa
        if "Your quick Tunnel has been created" in line:
            found_context = True

        #Busca una URL si ya se encontró el contexto relevante
        if found_context:
            match = re.search(r'https?://\S+', line)
            if match:
                url = match.group(0)  #Extrae la URL encontrada
                print(f'Tu aplicación está disponible en: {url}')
                break  #Termina el bucle después de encontrar la URL

!jupyter nbconvert --to script Aplicaciones_Termodinamicas.ipynb