# -*- coding: utf-8 -*-
"""TOBERAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BuLYvucuCy1Ez0oRvLnUg5LMRY_0NNHz
"""

#instalación de librerías
!pip install streamlit -q

!pip install browser-cookie3

!apt install ffmpeg -y

!pip install control -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile TOBERAS.py
# # pages/Tobera.py – Dashboard interactivo para análisis de tobera
# 
# import streamlit as st
# import numpy as np
# 
# # =========================
# # 🎨 Estilo Retro Gamer Azul (heredado)
# # =========================
# custom_css = """
# <style>
#     .stApp {background-color:#0D0F1A;color:#E0E0E0;font-family:'Courier New',monospace;}
#     h1,h2,h3{color:#00BFFF;text-shadow:0 0 10px #00BFFF;}
#     .main .block-container{padding-top:2rem;padding-bottom:2rem;background-color:#1B1D2B;border-radius:10px;}
#     section[data-testid="stSidebar"]{background-color:#151722;border-left:4px solid #00BFFF;border-radius:10px;}
# </style>
# """
# st.markdown(custom_css, unsafe_allow_html=True)
# 
# # =========================
# # 📝 Constantes globales
# # =========================
# R_kJ_kgK = 0.287   # kJ/kg·K
# Cp_kJ_kgK = 1.005  # kJ/kg·K
# 
# # =========================
# # 📝 Función de análisis de tobera
# # =========================
# 
# def analizar_tobera(P1_kPa, T1_C, V1_ms, A1_cm2, P2_kPa, V2_ms):
#     P1_Pa, P2_Pa = P1_kPa * 1000, P2_kPa * 1000
#     T1_K = T1_C + 273.15
#     A1_m2 = A1_cm2 / 1e4
# 
#     v1 = (R_kJ_kgK * 1000 * T1_K) / P1_Pa
#     m_dot = (A1_m2 * V1_ms) / v1
# 
#     Cp_J = Cp_kJ_kgK * 1000
#     delta_T = (V1_ms**2 - V2_ms**2) / (2 * Cp_J)
#     T2_K = T1_K + delta_T
#     T2_C = T2_K - 273.15
# 
#     v2 = (R_kJ_kgK * 1000 * T2_K) / P2_Pa
#     A2_m2 = (m_dot * v2) / V2_ms
#     A2_cm2 = A2_m2 * 1e4
# 
#     return {
#         "m_dot": m_dot,
#         "T2_C": T2_C,
#         "T2_K": T2_K,
#         "A2_cm2": A2_cm2,
#         "ratio": A2_m2 / A1_m2,
#         "v1": v1,
#         "v2": v2
#     }
# 
# # =========================
# # 🚀 Interfaz Streamlit
# # =========================
# st.set_page_config(page_title="Análisis de Tobera", page_icon="🚀", layout="wide")
# st.title("🚀 Dashboard Interactivo – Análisis de Tobera de Aire")
# 
# # =========================
# # 📘 Teoría
# # =========================
# with st.expander("📘 Fundamentos Termodinámicos de Toberas y Difusores (Çengel, 7ª ed.)"):
#     st.markdown(r"""
# Las **toberas** y los **difusores** son dispositivos fundamentales en sistemas de propulsión como motores a chorro, cohetes, turbinas de gas y también en aplicaciones industriales.
# - Una **tobera** incrementa la **velocidad del fluido** a costa de una **disminución de la presión**.
# - Un **difusor**, en cambio, **disminuye la velocidad** del fluido mientras **aumenta su presión**.
# 
# Ambos dispositivos están diseñados para modificar la energía cinética del fluido que los atraviesa, y **no implican trabajo mecánico** ($\dot{W} \equiv 0$), ni transferencia de calor significativa ($\dot{Q} \approx 0$), y el cambio de energía potencial es despreciable ($\Delta ep \approx 0$).
# 
# Por ello, la **conservación de energía** (1ª Ley de la Termodinámica para sistemas abiertos) se simplifica en estos casos a:
# 
# $$
# h_1 + \frac{V_1^2}{2} = h_2 + \frac{V_2^2}{2}
# $$
# 
# donde:
# - $h = C_p T$ es la entalpía específica
# - $V$ es la velocidad del flujo
# 
# Esto permite determinar la **temperatura de salida** $T_2$ si se conocen $T_1$, $V_1$ y $V_2$.
# 
# Asimismo, al aplicar la ecuación de conservación de masa:
# 
# $$
# \dot{m} = \frac{A_1 V_1}{v_1} = \frac{A_2 V_2}{v_2}
# $$
# 
# es posible calcular el **área de salida** $A_2$, siendo:
# - $v = \dfrac{RT}{P}$ el volumen específico del aire como gas ideal.
# 
# 📚 **Fuente**: Çengel, Yunus A., *Termodinámica*, 7ª Edición, McGraw-Hill, Sección 5.4 "Toberas y Difusores", pp. 278–279.
# """)
# 
# # =========================
# # 🧪 Ejercicio y Figura
# # =========================
# col1, col2 = st.columns(2)
# with col1:
#     with st.expander("🧪 Ejercicio Propuesto – Toberas"):
#         st.markdown("""
# **Primera ley de la termodinámica – Sistemas Abiertos**
# 
# **TOBERAS**
# 
# La entrada de una tobera tiene una sección de 100 cm², y por ella entra aire a una velocidad de 50 m/s, con una presión de 350 kPa y una temperatura de 227 °C. Luego sale a una velocidad de 190 m/s y una presión de 120 kPa. Determinar:
# 
# - a) El flujo másico de aire que circula por la tobera
# - b) La temperatura del aire a la salida de la tobera
# - c) El área de sección de salida de la tobera
# - d) La relación de áreas de entrada y salida
# """)
# with col2:
#     st.image("https://github.com/Jmontoyaor/thermodynamics/blob/main/Imagen%201.png?raw=true",
#              caption="**FIGURA 5-25** – La forma de toberas y difusores es tal que causan grandes cambios en la velocidad del fluido y, por lo tanto, en la energía cinética.\n\nFuente: Çengel – Termodinámica, 7ª Edición.")
# 
# # Sidebar – Parámetros de entrada
# tsidebar = st.sidebar
# tsidebar.header("📥 Parámetros de Entrada")
# P1 = tsidebar.number_input("Presión de entrada P₁ [kPa]", 50.0, 1000.0, 350.0, step=10.0)
# T1 = tsidebar.number_input("Temperatura de entrada T₁ [°C]", -50.0, 800.0, 227.0, step=5.0)
# V1 = tsidebar.number_input("Velocidad de entrada V₁ [m/s]", 1.0, 500.0, 50.0, step=1.0)
# A1 = tsidebar.number_input("Área de entrada A₁ [cm²]", 1.0, 1000.0, 100.0, step=1.0)
# P2 = tsidebar.number_input("Presión de salida P₂ [kPa]", 5.0, 1000.0, 120.0, step=5.0)
# V2 = tsidebar.number_input("Velocidad de salida V₂ [m/s]", 1.0, 1000.0, 190.0, step=1.0)
# 
# if tsidebar.button("💡 Calcular"):
#     res = analizar_tobera(P1, T1, V1, A1, P2, V2)
# 
#     st.subheader("📊 Resultados del Análisis")
#     st.metric("Flujo másico ṁ", f"{res['m_dot']:.3f} kg/s")
#     st.metric("Temperatura de salida T₂", f"{res['T2_C']:.2f} °C  ({res['T2_K']:.2f} K)")
#     st.metric("Área de salida A₂", f"{res['A2_cm2']:.2f} cm²")
#     st.metric("Relación de áreas A₂/A₁", f"{res['ratio']:.4f}")
# 
#     with st.expander("🔍 Detalles de los Cálculos"):
#         st.write(
#             f"""
#             - **Volumen específico entrada (v₁):** {res['v1']:.5f} m³/kg
#             - **Volumen específico salida (v₂):** {res['v2']:.5f} m³/kg
#             - **Constante del gas R:** {R_kJ_kgK} kJ/kg·K
#             - **Calor específico Cp:** {Cp_kJ_kgK} kJ/kg·K
#             """
#         )
# 
# # =========================
# # 👤 Créditos
# # =========================
# st.markdown("""
# ---
# ##### 👨‍💻 Desarrollado por **Juan Fernando Montoya Ortiz**
# """)
# 
#

!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
!mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

#Ejecutar Streamlit
!streamlit run TOBERAS.py &>/content/logs.txt & #Cambiar 0_👋_Hello.py por el nombre de tu archivo principal

#Exponer el puerto 8501 con Cloudflare Tunnel
!cloudflared tunnel --url http://localhost:8501 > /content/cloudflared.log 2>&1 &

#Leer la URL pública generada por Cloudflare
import time
time.sleep(5)  # Esperar que se genere la URL

import re
found_context = False  # Indicador para saber si estamos en la sección correcta

with open('/content/cloudflared.log') as f:
    for line in f:
        #Detecta el inicio del contexto que nos interesa
        if "Your quick Tunnel has been created" in line:
            found_context = True

        #Busca una URL si ya se encontró el contexto relevante
        if found_context:
            match = re.search(r'https?://\S+', line)
            if match:
                url = match.group(0)  #Extrae la URL encontrada
                print(f'Tu aplicación está disponible en: {url}')
                break  #Termina el bucle después de encontrar la URL